### PR TITLE
update: to v3 compat module and parse variables for actions

### PR DESCRIPTION
**Pull request by digitaldrummerj**
# Changes:

- update: module format to v3 module format
- update: timestamp that is less than an hour to start with 00: so that you can then sort the markers if the show is over an hour
- add: parsing of variables for create session for the database name and create marker for the message

#2

### CODE REVIEW

**Comment by josephdadams** [comment]
@digitaldrummerj Overall this is great! Couple of things:

1. consider adding yourself to `manifest.json` as a maintainer
2. convert all `var` usage to `let` since it doesn't look like they need to be scoped globally at any point.

**Comment by josephdadams** [comment]
Also does this close out issue #2?

**Comment by digitaldrummerj** [comment]
> Also does this close out issue #2?

It does not fully close it out since it was a list of several enhancements they would like to see and only a portion are included in this PR.  

It felt like rearranging the column order and sorting column was a change that needed discussed before implementation.  Same with the feedbacks since there was not any feedbacks today.

The two that were implemented and didn't feel like they would break anything existing were supporting variables in the action options and changing the timestamp to include the 00: hour when under an hour so you could sort on the timestamp column if you went over an hour.

**Comment by digitaldrummerj** [comment]
@josephdadams I added myself to the list of maintainers and changed the var to let.

**Pull request merged**
